<a href="https://colab.research.google.com/github/zsabro/PIAIC_ISLAMABAD_BATCH3/blob/master/Q2_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assighment 1 : 50 Numpy functions

In [ ]:
import numpy as np

# 1. Creating Simple array through array function

In [ ]:
a = np.array([1,2,3,4,5])



2. Creating an array by a numpy function

In [ ]:
import numpy as np

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


3. Creating multi dimensional array

In [ ]:
b = np.arange(15).reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


4. finding array dimensions

In [ ]:
b.ndim

2

5. Finding shape of an array

In [ ]:
b.shape

(3, 5)

6. finding data type of an array

In [ ]:
b.dtype

dtype('int64')

7. Finding buffer size of an array

In [ ]:
b.data

8. Making sequence of sequences

In [ ]:
c = np.array([(1,2,3,4,5), (6,7,8,9,0)])
c
print(c)

[[1 2 3 4 5]
 [6 7 8 9 0]]


# 9. Creating array where arrays are unknown but size is known

In [ ]:
d = np.zeros((2,3,3))
print(d)

e = np.ones((2,3,4))
e

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

10. To create series of numbers

In [ ]:
f = np.arange(1, 10, 2)
f
print(f)
g = np.arange(2, 6, 0.3)
g

[1 3 5 7 9]


array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6,
       5.9])

11. Using linespace function to create an array of equally distributed  float

In [ ]:
from numpy import pi
h = np.linspace(1, 10, 9)
print(h)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


12. Operation through operators

In [3]:
import numpy as np

i = np.array([2,4,8,6,10])
j = np.arange(5)
k = i - j
print(k)
l = i**3
print(l)



[2 3 6 3 6]
[   8   64  512  216 1000]


13. to check whether all elements in an array correspondence to true

In [6]:
np.all([3,2,1,0])

np.all([32, 0.5, -3])

True

reshape an array

In [28]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(x)
y = x.resize((3,2))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
None
